### ISSUE TITLE
Durable sink retained file limit

### ISSUE THREAD

**Issue by jblackburn21** [serilog/serilog-sinks-loggly#13]
The RollingFileSink in the DurableLogglySink supports the ability to set the retained file limit, but the current implementation passes in null, so it would be unlimited.  Would you accept a PR that would allow this to be overridden?

**Comment by MiguelAlho** [comment]
Sorry for the delayed response, but I don't believe I got a notification for this one. Yes, I can look into it if you send the PR, to help move that foward.

**Comment by MiguelAlho** [comment]
I'm working on a new item where i'll include this. I'll close this issue once it is completed

**Comment by jblackburn21** [comment]
Great.  Thanks!  I haven't had a chance to get back to it yet.

**Comment by MiguelAlho** [comment]
This is now in 5.0.0. Use the retainedFileCountLimit  argument to control this behaviour.
