### ISSUE TITLE
Will it work on dotnet core 2.1 environment for sending logs to Loggly?

### ISSUE THREAD

**Issue by Skawt15** [serilog/serilog-sinks-loggly#47]
Hi,

Just want to confirm if this library will work on sending logs to Loggly when the environment is dotnet core 2.1 SDK?

Best,
S

**Comment by mbp** [comment]
It does work.

**Comment by MiguelAlho** [comment]
Test project has been updated in https://github.com/serilog/serilog-sinks-loggly/pull/51 to reflect this
