### ISSUE TITLE
LogContext.PushProperty not included in the log output

### ISSUE THREAD

**Issue by JanKinable** [serilog/serilog-sinks-loggly#48]
The setting of the LogContext is not included in the message.
When I do the following
```
using (LogContext.PushProperty("app", "my-app"))
{
     log.Debug("Debug Message at {time}", DateTime.Now);
}
```
I see next (raw) message arrive at Loggly:
`
{"Message":"Debug Message at 02/18/2019 11:41:02","time":"02/18/2019 11:41:02","Level":"Debug","timestamp":"2019-02-18T11:41:02.3620794+00:00"}
`
I'm missing the "app" property from the message, expected:
`
{"Message":"Debug Message at 02/18/2019 11:41:02","time":"02/18/2019 11:41:02","app":"my-app","Level":"Debug","timestamp":"2019-02-18T11:41:02.3620794+00:00"}
`

**Comment by MiguelAlho** [comment]
I added a bit of code to the sample project (#51) to simulate this.  In the live tail,  the added property is showing up:

´´´
X-Forwarded-For:0.0.0.0, 0.0.0.0, X-Real-IP:0.0.0.0, Content-Type:application/json; charset=utf-8, tag:application-serilogSample, tag:host-PRTLAPCMWX2M2 ] {"Message":"message to send with { P1: \"sample4\", P2: 2019-12-23 14:30:01.037 }","Data":{"P1":"sample4","P2":"2019-12-23 14:30:01.037"},**"sampleProperty":"Sample Value"**,"ProcessId":8956,"ThreadId":1,"EnvironmentUserName":"----","MachineName":"----","Environment":"development","Level":"Information","timestamp":"2019-12-23T14:30:01.0371065+00:00"}
´´´
